# nanodet-plus-m_416
# COCO mAP(0.5:0.95) = 0.304
#             AP_50  = 0.459
#             AP_75  = 0.317
#           AP_small = 0.106
#               AP_m = 0.322
#               AP_l = 0.477
save_dir: workspace/cpu_beta
model:
  arch:
    name: OneStageDetector
    backbone:
      name: MobileNetV2
      width_mult: 1.0
      out_stages: [2, 4, 6]
      activation: ReLU6
    fpn:
      name: PAN
      in_channels: [32, 96, 320]
      out_channels: 32
      start_level: 0
      num_outs: 3
    head:
      # name: NanoDetPlusHead
      name: NanoDetHead
      num_classes: 2
      input_channel: 32
      feat_channels: 32
      activation: ReLU6
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0

class_names:  &class_names ['Fire', 'Smoke']

data:
  train:
    name: YoloDataset
    img_path: beta-dts-fsd/train/images
    ann_path: beta-dts-fsd/train/images
    class_names: *class_names
    input_size: [256,160] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[0.8, 1.2], [0.8, 1.2]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: YoloDataset
    img_path: beta-dts-fsd/valid/images
    ann_path: beta-dts-fsd/valid/images
    class_names: *class_names
    input_size: [256,160] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 4
  batchsize_per_gpu: 32
schedule:
  # resume: False
  # load_model: workspace/cpu_beta/model_last.ckpt
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  total_epochs: 300
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 300
    eta_min: 0.00005
  val_intervals: 1
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 50

